### ISSUE TITLE
Self-service deployment issue

### ISSUE THREAD

**Issue by Sigvelli** [microsoft/2LCS#31]
I recently created a new LCS project and this project seems a little bit different than previous LCS projects. I am no longer able to log in to a Tier 2 environment using RDP. The new functionality is described in "Self-service deployment overview"  https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/infrastructure-stack

The result of this LCS change is that 2LCS is not getting access to Tier2 "MS-hosted environments". Tier2 environments are no longer visible in 2LCS.

**Comment by TomekMelissa** [comment]
Self-service environments do not have RDP access by design. It is clearly stated in the documentation you linked. I do no have access to a project of this type at the moment. When I get it I will introduce changes to 2LCS, so at least we will be able to see those instances on the list in 2LCS. I think it should be possible. RDP access is gone though.
