### ISSUE TITLE
Release 0.20.0 is not stabile

### ISSUE THREAD

**Issue by Sigvelli** [microsoft/2LCS#33]
Release 0.20.0 is not as stabile as release 0.19.0 is.
I am sorry to say that this version is crashing too often. Release 19 is very stable!

I was able to locate the new "Azure DevOps" menu, but no Sharepoint site was visible to me.

**Comment by TomekMelissa** [comment]
Could you please download the package again and see if your problems persist? I uploaded new 0.20.0 package shortly after I released its first bits. Due to code cleanup I encountered some unexpected errors. 
If you will still experience the same problems please be more specific.

About Sharepoint menu item. Are you sure you have Sharepoint configured in your LCS project?

**Comment by TomekMelissa** [comment]
I think I found the problem or at least one of them. Please check 0.21.0 and let me know. I have very limited testing capabilities and there are LCS project configurations that I am not able to test myself.

**Comment by Sigvelli** [comment]
I have tested version 0.21.0 for a few days. It seems solid as a rock! I love the "Azure DevOps site" menu that has been added. Thanks.

**Comment by Sigvelli** [comment]
About the "Azure DevOps site" menu. When changing to another LCS project, the DevOps site remains the same.
