### ISSUE TITLE
.NET core and Process.start

### ISSUE THREAD

**Issue by fraga** [microsoft/2LCS#77]
Tracking an issue here where we can't "Log on" to the environment. I believe we just need to change the implementation to just call default browser. 

![image](https://github.com/microsoft/2LCS/assets/303538/f56a94d6-bfcf-43e5-ac6d-d59589be8d00)

I should be able to pull request later tonight

**Comment by FH-Inway** [comment]
Thanks for reporting, I was able to repro on my end. The issue affects all function that open a web page. It is caused by a change in behavior between .NET Framework and .NET. See https://github.com/dotnet/runtime/issues/28005#issuecomment-485532113

#78 has a fix. The [build](https://github.com/microsoft/2LCS/actions/runs/5834073047) for that pr has a [2LCS.zip](https://github.com/microsoft/2LCS/suites/15020712593/artifacts/857592355) file that can be used to test the fix.

**Comment by fraga** [comment]
Awesome! Code looks good! I guess we can close the issue.

**Comment by FH-Inway** [comment]
Thanks. I created [release 0.42.0](https://github.com/microsoft/2LCS/releases/tag/v.0.42.0) with this fix.
